### ISSUE TITLE
placed state get corrupted on sort

### ISSUE THREAD

**Issue by aholtzma** [oceanofthelost/InteractiveBOM#7] opened 2019-03-18 15:03 UTC
If you click on a column to change the sort order, the state of the placed check boxes get corrupted. To reproduce this, load up a pcb, check the placed box on the first line item, and then sort by the References column. When I do that, I get half a dozen checked boxes in the Placed column.

**Comment by oceanofthelost** [comment] 2019-03-18 15:26
Thank you for mentioning this. This is a bug and is filed as BUG0003. I
will add your information to the bug report.

**Comment by oceanofthelost** [comment] 2019-03-23 17:19
This is a duplicate of issue #8. The corrupt button state is fixed in 17c216e209647d1cb242857e28514bf8e4335fd.

**Closed** 2019-03-23 17:19 UTC
Labels: bug
